name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    permissions:
      id-token: write
      contents: write
      security-events: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Clone upstream repo
        uses: actions/checkout@v3
        with:
          repository: 'mlflow/mlflow'
          ref: 'v2.1.1'
          path: './upstream'
      
      - name: Move edited Dockerfile
        run: |
          cp ./Dockerfile ./upstream/Dockerfile

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker image
        run: |
          cd upstream
          docker build -t ${{ secrets.DOCKER_HUB_IMAGE }}:latest .
      
      - name: Run image tests
        run: |
          docker run --rm -it -p 5000:5000 -d ${{ secrets.DOCKER_HUB_IMAGE }}:latest mlflow server --host 0.0.0.0
          sleep 5
          curl -I --fail localhost:5000
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_HUB_IMAGE }}:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          timeout: '30m'
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Docker push image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_HUB_IMAGE }}:latest
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3